name: Schedule

on:
   schedule:
     - cron: "0/5 * * * *"
     - cron: "0/7 * * * *"
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a



